Repository Berted/coNote, pull requests merged in 2022-06, with the labels that each got.

#20 Adds CRUD docs (title) functionality
  .gitignore
  conote-frontend/package-lock.json
  conote-frontend/package.json
  conote-frontend/src/components/Home.tsx
  conote-frontend/src/components/Logo.tsx
  conote-frontend/src/components/NavbarContainer.tsx
  conote-frontend/src/components/interfaces/docType.tsx
  conote-frontend/src/components/interfaces/userType.tsx
  conote-frontend/src/components/user/Dashboard.tsx
  conote-frontend/src/components/user/Userform.tsx
  database.rules.json
  firebase.json
Labels: enhancement

#28 Add forget password feature
  conote-frontend/src/App.tsx
  conote-frontend/src/components/user/Forgetpassword.tsx
Labels: enhancement

#31 Add display warnings on login/signup/reset password success/failure
  conote-frontend/src/App.tsx
  conote-frontend/src/components/user/ForgetPassword.tsx
  conote-frontend/src/components/user/Login.tsx
  conote-frontend/src/components/user/Loginform.tsx
  conote-frontend/src/components/user/PasswordInput.tsx
  conote-frontend/src/components/user/Signup.tsx
  conote-frontend/src/components/user/Signupform.tsx
Labels: enhancement

#33 Minor Code Refactoring
  conote-frontend/src/components/user/Dashboard.tsx
  conote-frontend/src/components/user/DashboardNavbar.tsx
  conote-frontend/src/components/user/DocCard.tsx
  conote-frontend/src/components/user/UserButton.tsx
  conote-frontend/src/hooks/useAuth.tsx
Labels: maintainance

#34 Add button to add/edit tags for documents
  conote-frontend/src/components/user/DocCard.tsx
Labels: enhancement

#37 Adds menu to set access levels for documents
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/hooks/useAuth.tsx
Labels: enhancement

#48 Add code highlighting on Markdown renderer
  conote-frontend/public/index.html
  conote-frontend/src/components/editor/Editor.tsx
Labels: enhancement, minor

#53 Add public view checkmark
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/components/editor/useFirepad.tsx
  conote-frontend/src/components/user/Dashboard.tsx
  conote-frontend/src/components/user/UserButton.tsx
  conote-frontend/src/hooks/useAuth.tsx
Labels: enhancement

#56 Add file export support
  conote-frontend/package-lock.json
  conote-frontend/package.json
  conote-frontend/public/index.html
  conote-frontend/public/print.css
  conote-frontend/src/components/NavbarContainer.tsx
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/components/editor/ExportButton.tsx
  conote-frontend/src/components/editor/MarkdownPreview.tsx
  conote-frontend/src/components/user/UserButton.tsx
Labels: enhancement

#58 Add Raw HTML + Table of Content Support
  conote-frontend/package-lock.json
  conote-frontend/package.json
  conote-frontend/src/components/editor/MarkdownPreview.tsx
Labels: enhancement
