Repository Berted/coNote, pull requests merged in 2022-07, with the labels that each got.

#74 Add Dynamic Page Headers
  conote-frontend/package-lock.json
  conote-frontend/package.json
  conote-frontend/public/favicon.ico
  conote-frontend/public/favicon.svg
  conote-frontend/public/index.html
  conote-frontend/public/logo192.png
  conote-frontend/public/logo512.png
  conote-frontend/public/manifest.json
  conote-frontend/src/components/ErrorPage.tsx
  conote-frontend/src/components/Home.tsx
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/user/Dashboard.tsx
  conote-frontend/src/components/user/ForgetPassword.tsx
  conote-frontend/src/components/user/Login.tsx
  conote-frontend/src/components/user/Signup.tsx
Labels: enhancement, minor

#75 Fix Timestamp Bug
  conote-frontend/package-lock.json
  conote-frontend/package.json
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/components/editor/useFirepad.tsx
Labels: bug

#76 Add shared documents page
  conote-frontend/package-lock.json
  conote-frontend/package.json
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/components/editor/useFirepad.tsx
  conote-frontend/src/components/interfaces/userType.tsx
  conote-frontend/src/components/user/Dashboard.tsx
  conote-frontend/src/components/user/DashboardNavbar.tsx
  conote-frontend/src/components/user/DocCard.tsx
Labels: enhancement

#77 Fix anchor link bug
  conote-frontend/src/components/editor/MarkdownPreview.tsx
  conote-frontend/src/components/editor/anchorLink.css
Labels: bug

#80 Adds User Presence and Cursor
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/components/editor/useFirepad.tsx
  conote-frontend/src/components/editor/userPresence/CursorHandler.tsx
  conote-frontend/src/components/editor/userPresence/UserPresenceAvatars.tsx
  conote-frontend/src/components/editor/userPresence/UserPresenceHandler.tsx
  conote-frontend/src/components/editor/userPresence/cursorPlugin.tsx
  conote-frontend/src/components/editor/userPresence/cursorSelectionMark.tsx
  conote-frontend/src/components/editor/userPresence/cursorStateEffects.tsx
  conote-frontend/src/components/editor/userPresence/cursorTooltipFonts.css
  conote-frontend/src/components/editor/userPresence/selectionPlugin.tsx
  conote-frontend/src/components/user/UserButton.tsx
  conote-frontend/tsconfig.json
Labels: enhancement

#85 Add landing page for reset password
  conote-frontend/src/App.tsx
  conote-frontend/src/components/user/ForgetPassword.tsx
  conote-frontend/src/components/user/ResetPassword.tsx
  conote-frontend/src/hooks/useAuth.tsx
Labels: enhancement

#91 Adds Text on No Documents
  conote-frontend/src/components/styles/noselect.css
  conote-frontend/src/components/user/Dashboard.tsx
Labels: enhancement, minor

#92 Adds Tooltips on Export HTML and Raw-HTML
  conote-frontend/src/components/editor/ExportButton.tsx
Labels: documentation

#90 Fix Empty Document Title Bug
  conote-frontend/src/components/user/DashboardNavbar.tsx
  conote-frontend/src/components/user/DocCard.tsx
Labels: bug

#93 Increases User Cursor Hover Area
  conote-frontend/src/components/editor/userPresence/cursorPlugin.tsx
Labels: enhancement, minor

#96 Fix misc. bugs with documents view
  conote-frontend/src/components/user/Dashboard.tsx
  conote-frontend/src/components/user/DocCard.tsx
Labels: bug

#89 Add edit user profile functionality
  conote-frontend/src/components/editor/userPresence/UserPresenceAvatars.tsx
  conote-frontend/src/components/editor/userPresence/UserPresenceHandler.tsx
  conote-frontend/src/components/user/Login.tsx
  conote-frontend/src/components/user/PasswordInput.tsx
  conote-frontend/src/components/user/Signup.tsx
  conote-frontend/src/components/user/UserButton.tsx
  conote-frontend/src/hooks/useAuth.tsx
Labels: enhancement

#95 Editor image support
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/components/editor/UploadImageButton.tsx
  conote-frontend/src/components/user/DocCard.tsx
Labels: enhancement

#102 Minor Bug Fixes for Markdown Rendering
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/editor/MarkdownPreview.tsx
Labels: bug

#103 Add redirect from document to login page if not signed in
  conote-frontend/src/components/editor/EditorNavbar.tsx
  conote-frontend/src/components/editor/useFirepad.tsx
  conote-frontend/src/components/interfaces/queryStringType.tsx
  conote-frontend/src/components/user/Dashboard.tsx
  conote-frontend/src/components/user/Login.tsx
Labels: enhancement

#106 Bug Fixes
  conote-frontend/src/components/editor/Editor.tsx
  conote-frontend/src/components/editor/MarkdownPreview.tsx
  conote-frontend/src/components/editor/UploadImageButton.tsx
Labels: bug
